### ISSUE TITLE
Flat cache format

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#110]
- [x] Unpacking from cache to flat files
- [ ] Packing flat files to cache
- [ ] Converting files to different flat formats
- [ ] Storing details in custom opcode (like parameters but also allows encoding doubles/booleans/enums/arrays)

**Comment by Tyluur** [comment]
Odd place to have stopped this at.

**Comment by GregHib** [comment]
Was having problems with kotlinx serialization. They're probably resolved now but this task isn't worth the effort.
