### ISSUE TITLE
Item equip types from cache

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#155]
Need to compare but the BodyParts EquipType data can be found in item defs

624 - hats
625 - hair

**Comment by Tyluur** [comment]
No, It's not in the item definitions natively.

**Comment by GregHib** [comment]
It is in higher revisions, see `ItemDecoder718` and `ItemDefinitionsParamConverter` although it wouldn't make sense why it has that information in there twice. Anyway, this ticket is a todo; Check/Explore

**Comment by Tyluur** [comment]
> It is in higher revisions, see `ItemDecoder718` and `ItemDefinitionsParamConverter` although it wouldn't make sense why it has that information in there twice. Anyway, this ticket is a todo; Check/Explore

Since void is made with a 634 client build, you'll have to store newer item equip type data in a local repository then.

**Comment by GregHib** [comment]
> Since void is made with a 634 client build, you'll have to store newer item equip type data in a local repository then.

`ItemDefinitionsParamConverter` packs the data from one cache into another, that's the whole idea behind #110; easily add and modify cache data rather than having a load of extra config files to load on startup.

**Comment by GregHib** [comment]
Only looks like these two params.
They don't line up with current data of what is a hat/needs hair removing.
A way of identifying a sub-set of hats and masks.
Doesn't seem to be useful.
