### ISSUE TITLE
Smithing

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#255]
- [x] Smelting bars
- [x] Smithing items
- [x] Superheat item
- [x] Cannonballs

**Comment by GregHib** [comment]
Ring of forging depends on #311

**Comment by NickRahn** [comment]
is smithing working? I just tested at Varrock west bank using a bronze bar on an anvil and nothing interesting happens

**Comment by GregHib** [comment]
> is smithing working? I just tested at Varrock west bank using a bronze bar on an anvil and nothing interesting happens

Yes but currently only works on anvils added in objects.yml, so currently just lumbridge
