### ISSUE TITLE
Change the order hits are processed

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#273]
Hits should be processed individually per character and before the rest of the combat cycle so that pid actually matters.

Should be resolved by #283 as hits are strongly queued.

**Comment by GregHib** [comment]
If A is fighting B

Both players send the attack option on the same tick.

A has a higher index so A's instruction get's processed first
They get the skull and start attacking B
B then get's processed and retaliates

**How it currently works:**

A's combat action got queued first so it goes first
Calculations are done and a hit is applied to B
B's turn and a hit is applied to A

**How it should work:**

A has a higher index so A's combat cycle starts
A checks if it has any hits to apply: it does not
A takes a swing and adds a hit to B's hit queue
B's turn to process
B checks if it has any hits to apply: It does so it applies A's hits
B takes a swing and adds a hit to A's hit queue.

B's hit on A's doesn't get applied until the following tick.

**Comment by Tyluur** [comment]
Useful explanation, cheers.
