### ISSUE TITLE
Fix displee's cache lib

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#322]
Doesn't fully garbage collect cause of an array in the gzip object? Leaves 50mb behind.

**Comment by advnau** [comment]
https://github.com/Displee/rs-cache-library/blob/master/src/main/kotlin/com/displee/compress/type/GZIPCompressor.kt#L14 It creates an array of a fixed size that is only used on 317 archive reading. 

Unfortunately this is set as a val so we cant really do a kt extension function to clear the value.

Possible solutions include 
1) submitting a PR to add ability to null out the buffer when loading a new format cache w/ reference tables.
2) submit a PR that adds a way to lazily initialize the array only when the 317 specific method is called.
3) Doing some reflection to get the value and set to null like below. Edit: After checking into this more, it doesnt seem to be a viable option.

        val field = GZIPCompressor::class.java.getDeclaredField("gzipBuffer")
        field.isAccessible = true
        field.set(GZIPCompressor, null) //we might have to pass field.set(null, null), not completely sure on how kt handles instancing.

**Comment by GregHib** [comment]
Yep my plan was to submit a PR. 2. probably sounds best although I haven't looked at it in any detail

**Comment by GregHib** [comment]
https://github.com/Displee/rs-cache-library/pull/51

The main issue has been already solved, converting the rest of compressors only saves 2MB extra but I did it anyway. Awaiting review, merge and release

**Comment by GregHib** [comment]
Fix is merged and written a new lighter cache reader anyway
