### ISSUE TITLE
Add combination runes

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#399]
https://runescape.wiki/w/Combination_rune

- [ ] Use combination runes in spells instead of elemental
- [ ] Create combation runes at altar
- [ ] Binding necklace bonus https://runescape.wiki/w/Binding_necklace

**Comment by Syntax2022** [comment]
Is this being worked on?

**Comment by GregHib** [comment]
Not currently, what I work on I try to keep up-to-date in https://github.com/GregHib/void/projects/1
