### ISSUE TITLE
Help with handling Object replacing

### ISSUE THREAD

**Issue by Syntax2022** [GregHib/void#449]
**Describe the bug**
Not a bug, just seeking information on how GameObjects#replace() works

**To Reproduce**
I had taken the code from Woodcutting.kt that handles when a tree depletes: 

firstObj = first object (One that will be replaced)
secondObj = "The object that 'firstObj' will be replaced with"

`private fun changeTreeStage(firstObj: GameObject, secondObj: GameObject): Boolean {
        if (definitions.contains(secondObj.id)) {
            println("replacing object")
            objects.replace(firstObj, secondObj)
            return true
        }
        return false
    }`

**Expected behavior**
When calling the above method i would expect the object to be replaced with a new object on the original objects tile. but that doesn't seem to be working i need to log out and back in 

**Screenshots**
Before the player had relogged and the object replace function has been ran (Object not updated)
![before](https://github.com/GregHib/void/assets/79747812/92161c32-a44f-45c5-8066-1fe16308c27a)

After the player has relogged (Object updated)
![after](https://github.com/GregHib/void/assets/79747812/4969bf7b-d984-41fa-9994-10b191dd185b)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04.3 LTS
 - JDK Version: 21.0.2

**Additional context**
I initially was looking at Delrith.kts and tried to use that method of changing objects but i thought it may be different because that was handling a cutscene, so then i looked into other methods that may replace objects that's when i repurposed code that already exists. i made sure that the object's are inside **objects.yml** (because initially they weren't) I also as a test replaced the **stumpId** in the woodcutting class to a random object and that seemed to have worked, there's no issues with adding objects to the world, only when removing or replacing that requires me to re log and i presume i am missing some update function, but i was unable to trace it in the woodcutting or mining classes

**Comment by GregHib** [comment]
Hi, make sure you're using the existing `GameObject`:

```kotlin
val existing = objects.get(player.tile, "evil_tree_sapling_1")
if (existing != null) {
    existing.replace("evil_tree_sapling_2")
}
```
Something like ^ should work. Where something like `objects.replace(GameObject(11391, 3200, 3200, 0, 10, 0), GameObject(11392, 3200, 3200, 0, 10, 0))` might not.

If that's still not working could you please provide the replaced code you're using to call `changeTreeStage`, and what you have in objects.yml too

**Comment by Syntax2022** [comment]
Hello, thanks for replying what you had given me didn't seem to work here's how i am calling the **changeTreeStage**

SaplingStage Class:
```kotlin
    val EVIL_TREE_SEEDLING: String = "evil_tree_seedling"

    val EVIL_TREE_SAPLING: String = "evil_tree_sapling"
    val EVIL_TREE_SAPLING_2: String = "evil_tree_sapling_2"

    val EVIL_TREE_YOUNG: String = "evil_young_tree"
    val EVIL_TREE_YOUNG_2: String = "evil_young_tree_2"
    
    
```

I have a update function that runs the changeTreeStage every x seconds which parses the above variables depending on the current stage 

```kotlin
val tile = Tile(3222, 3219)
val first = GameObject(11391, tile, 10, 0) // temp
private val elapsedTimeIncrement = 1
    private val upgradeTime1 = 20
    private val upgradeTime2 = 40
    private val upgradeTime3 = 50

override fun update() {
        when (elapsedTime) {
            0 -> addObject(first)
           upgradeTime1 -> changeTreeStage(EVIL_TREE_SEEDLING, EVIL_TREE_SAPLING)
            upgradeTime2 -> changeTreeStage(EVIL_TREE_SAPLING, EVIL_TREE_SAPLING_2)
            upgradeTime3 -> changeTreeStage(EVIL_TREE_SAPLING_2, EVIL_TREE_YOUNG)
        }
        elapsedTime += elapsedTimeIncrement
        println("sapling updating $elapsedTime")
    }
```

and finally the changes i had made to the code you gave me above looks like the following:

```kotlin
private fun changeTreeStage(oldTree: String, newTree: String): Boolean {
        val existing = objects.get(tile, oldTree)
        if(existing != null){
            print("object exists")
            existing.replace(newTree)
            return true
        }
        return false
    }

```
and heres what i have inside the objects.yml file

```yml
evil_tree_seedling:
    id: 11391
    examine: "change me"
evil_tree_sapling:
  id: 11392
  examine: "change me"
evil_tree_sapling_2:
  id: 11393
  examine: "change me"
evil_young_tree:
  id: 11394
  examine: "change me"
evil_young_tree_2:
  id: 11395
  examine: "change me"
```

Thanks in advanced

**Comment by GregHib** [comment]
I have assumed your `addObject` does the same as `objects.add()` as you haven't provided it, however I have tested it out with a command and it seems to be working as expected, can you confirm if this code also works for you?

```kotlin
val EVIL_TREE_SEEDLING: String = "evil_tree_seedling"

val EVIL_TREE_SAPLING: String = "evil_tree_sapling"
val EVIL_TREE_SAPLING_2: String = "evil_tree_sapling_2"

val EVIL_TREE_YOUNG: String = "evil_young_tree"
val EVIL_TREE_YOUNG_2: String = "evil_young_tree_2"

private val elapsedTimeIncrement = 1
private val upgradeTime1 = 2
private val upgradeTime2 = 4
private val upgradeTime3 = 5
var elapsedTime = 0
val tile = Tile(3222, 3219)

adminCommand("eviltree") {
    when (elapsedTime) {
        0 -> objects.add(GameObject(11391, tile, 10, 0))
        upgradeTime1 -> changeTreeStage(EVIL_TREE_SEEDLING, EVIL_TREE_SAPLING)
        upgradeTime2 -> changeTreeStage(EVIL_TREE_SAPLING, EVIL_TREE_SAPLING_2)
        upgradeTime3 -> changeTreeStage(EVIL_TREE_SAPLING_2, EVIL_TREE_YOUNG)
    }
    elapsedTime += elapsedTimeIncrement
    println("sapling updating $elapsedTime")
}

private fun changeTreeStage(oldTree: String, newTree: String): Boolean {
    val existing = objects.get(tile, oldTree)
    if (existing != null) {
        print("object exists")
        existing.replace(newTree)
        return true
    }
    return false
}
```

I would guess `override fun update()` isn't getting called as expected.

**Comment by Syntax2022** [comment]
yes i can confirm that this code works as expected, and the ```override fun update()``` is being called correctly, there's something i must be doing wrong, because it changes the object fine through the command but when running it in my update function doesn't seem to work i am going to change my implementation and see if that works thank you for your help

**Comment by GregHib** [comment]
No problem, a few extra things you might find useful as they're not entirely obvious (I'm writing these kinds of things in the [wiki](https://github.com/GregHib/void/wiki) atm):

1. There is a world timer that can be used; `World.run`. They can be chained to make a less frequent tick as is done [here in restocking](https://github.com/GregHib/void/blob/a4af3f90fdc33c890935abc9531f903e06b1a6d0/game/src/main/kotlin/world/gregs/voidps/world/interact/entity/npc/shop/Restock.kts#L60). I've decided there needs to be an easier way to do this though.

2. You can store the update times on the object definition itself in `objects.yaml`. Which can be accessed like `object.def["upgrade_time", -1]` where -1 is the default value.

```yaml
evil_tree_seedling:
  id: 11391
  upgrade_time: 20
  examine: "change me"
```

3. Might be an idea to name the objects something like `evil_tree_stage_1`, `evil_tree_stage_2` etc... that way you don't have to manually specify all the sapling names.



And combined you should be able to do something like this:

```kotlin
worldSpawn { 
    val firstTree = objects.add("evil_tree_stage_1", tile)
    growTree(firstTree)
}

fun growTree(currentTree: GameObject) {
    val updateTime = currentTree.def["upgrade_time", -1]
    if (updateTime == -1) {
        // do something now it's fully grown ...
        return
    }
    World.run("evil_tree_growth", updateTime) {
        val stage = currentTree.id.takeLast(1)
        val nextStage = currentTree.id.replace(stage, (stage.toInt() + 1).toString())
        val nextTree = currentTree.replace(nextStage)
        growTree(nextTree)
    }
}
```

Lmk if you still can't get it working or create a new issue if you run into anything else

**Comment by Syntax2022** [comment]
Thank you got everything working
