### ISSUE TITLE
MakeAmount usage

### ISSUE THREAD

**Issue by Syntax2022** [GregHib/void#512]
Hello, I am working on Fletching and when Fletching bows, There's a make dialogue where the player selects an option, I have repurposed the make code from else where in void but I can't seem to get it to work for `itemonItem` interactions

This is the code I currently have; 

```kotlin
itemOnItem("knife", "logs") {
    val usedLog = if (toItem.log) toItem else fromItem
    it.weakQueue("fletching_make_dialog") {
        val (selected, amount) = makeAmount(
                listOf("arrow_shaft", "shortbow_u", "longbow_u", "wooden_stock"),
                type = "Make",
                maximum = 10,
                text = "Test fletch"
        )
        //fletch(player, selected, amount)
        it.message("Selected: $selected Amount: $amount")
    }
}
```

When using the knife on the logs the make-x interface displays as expected but then clicking an option for example `arrow_shaft` nothing seems to happened when either calling `fletch` or sending a message to the player ingame. 

![makeinter](https://github.com/GregHib/void/assets/79747812/26c2123b-e449-4484-b948-31296a0f72f1)

Thanks in advance for the help.

**Comment by jarryd229** [comment]
i just changed it.message to player.message and it is showing for me if that is not the thing you need im not the best with this stuff sorry

**Comment by GregHib** [comment]
Same, the snippet works fine for me too. Do you perhaps have some additional itemOnItem calls which could be interfering/overriding the behaviour?

**Comment by Syntax2022** [comment]
interesting, the only `itemonItem` code i have is the code for making darts and bolts, but that shouldn't be overriding this? just to clarify, for you guys the dialog closes and displays the selected item and amount in chat? If that's the case i will try a fresh project.

**Comment by jarryd229** [comment]
yer it closes and shows in chatbox

**Comment by Syntax2022** [comment]
I found the issue, i noticed that the terminal was throwing this error `[DialogueContinueHandler] - Dialogue 905 not found for player Player(1, index=1, tile=Tile(2849, 3542, 2))` and then i remembered that i was playing around with `interfaces.yml` to learn how they worked, after removing what i added which was a duplicated interface with the ID 905 it works as expected, so sorry about that, it was actually my mistake and i should have remembered i was playing around with interface code.

**Comment by jarryd229** [comment]
its fine its how you learn

**Comment by GregHib** [comment]
Haha no worries
