### ISSUE TITLE
General store merchants missing

### ISSUE THREAD

**Issue by NickRahn** [GregHib/void#552]
**Describe the bug**
It appears that the merchants servicing merchant stores and possibly others are missing

**To Reproduce**
go to varrock, falador , edgeville, etc (i have only tested those 3) and go the general store location. the merchant is not there

**Expected behavior**
the merchant should be an NPC walking around to trade with

**Screenshots**
![image](https://github.com/user-attachments/assets/a5dca27d-a5c1-417c-997f-5ea3fea44473)

**versions**
 - void-client-0.0.7
 - void-server-1.2.3
 - windows env

**Additional context**
was looking to buy a hammer and noticed it is missing. also could not find a hammer anywhere?

**Comment by jarryd229** [comment]
hi void is still in development most npcs are not added yet only lumbridge is mostly added you can find a hammer in the lumbridge General Store
