### ISSUE TITLE
Network Flooder

### ISSUE THREAD

**Issue by GregHib** [GregHib/void#96]
A flooder to stress test and benchmark core systems in a more realitic environment.

Critera:
* Concurrently log in 2,000 player connections
* On connect send a teleport request to a place, with an overal customisable distribution (aka; random, even, dense, sparse)
* 25% of sessions sending appearance block re-rendering packet every tick (something like equip/unequip)
* 25% of sessions sending movement (pathfinding) packet every tick

> Note: the number of npc's pressent should also be taken into account when testing, although this isn't controlled by the flooder.

**Comment by Tyluur** [comment]
Is this to be done by simulating the client network?

**Comment by GregHib** [comment]
Yeah headless clients, however as networking is no longer a priority for this project this ticket can be closed.
